version: "2"

run:
  timeout: 5m
  tests: false

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - forcetypeassert
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - gosec
    - misspell
    - noctx
    - nolintlint
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    - unconvert
    - unparam
    - whitespace

  settings:
    gocyclo:
      min-complexity: 15
    govet: {}
    gocognit:
      min-complexity: 40
    goconst:
      min-occurrences: 20
    funlen:
      lines: 75
      statements: 50
    misspell:
      locale: US
    nolintlint:
      allow-unused: false
      require-explanation: true
      require-specific: false
