// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package index

import (
	"context"
	"sync"
)

// Ensure, that AWSIndexFetchMock does implement AWSIndexFetch.
// If this is not the case, regenerate this file with moq.
var _ AWSIndexFetch = &AWSIndexFetchMock{}

// AWSIndexFetchMock is a mock implementation of AWSIndexFetch.
//
// 	func TestSomethingThatUsesAWSIndexFetch(t *testing.T) {
//
// 		// make and configure a mocked AWSIndexFetch
// 		mockedAWSIndexFetch := &AWSIndexFetchMock{
// 			GetImagesFunc: func(ctx context.Context, opts FilterOpts) (AWSImages, error) {
// 				panic("mock out the GetImages method")
// 			},
// 		}
//
// 		// use mockedAWSIndexFetch in code that requires AWSIndexFetch
// 		// and then make assertions.
//
// 	}
type AWSIndexFetchMock struct {
	// GetImagesFunc mocks the GetImages method.
	GetImagesFunc func(ctx context.Context, opts FilterOpts) (AWSImages, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetImages holds details about calls to the GetImages method.
		GetImages []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Opts is the opts argument value.
			Opts FilterOpts
		}
	}
	lockGetImages sync.RWMutex
}

// GetImages calls GetImagesFunc.
func (mock *AWSIndexFetchMock) GetImages(ctx context.Context, opts FilterOpts) (AWSImages, error) {
	if mock.GetImagesFunc == nil {
		panic("AWSIndexFetchMock.GetImagesFunc: method is nil but AWSIndexFetch.GetImages was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Opts FilterOpts
	}{
		Ctx:  ctx,
		Opts: opts,
	}
	mock.lockGetImages.Lock()
	mock.calls.GetImages = append(mock.calls.GetImages, callInfo)
	mock.lockGetImages.Unlock()
	return mock.GetImagesFunc(ctx, opts)
}

// GetImagesCalls gets all the calls that were made to GetImages.
// Check the length with:
//     len(mockedAWSIndexFetch.GetImagesCalls())
func (mock *AWSIndexFetchMock) GetImagesCalls() []struct {
	Ctx  context.Context
	Opts FilterOpts
} {
	var calls []struct {
		Ctx  context.Context
		Opts FilterOpts
	}
	mock.lockGetImages.RLock()
	calls = mock.calls.GetImages
	mock.lockGetImages.RUnlock()
	return calls
}
