// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package index

import (
	"context"
	"sync"
)

// Ensure, that ContainerIndexFetchMock does implement ContainerIndexFetch.
// If this is not the case, regenerate this file with moq.
var _ ContainerIndexFetch = &ContainerIndexFetchMock{}

// ContainerIndexFetchMock is a mock implementation of ContainerIndexFetch.
//
// 	func TestSomethingThatUsesContainerIndexFetch(t *testing.T) {
//
// 		// make and configure a mocked ContainerIndexFetch
// 		mockedContainerIndexFetch := &ContainerIndexFetchMock{
// 			GetImagesFunc: func(ctx context.Context) (ContainerImages, error) {
// 				panic("mock out the GetImages method")
// 			},
// 		}
//
// 		// use mockedContainerIndexFetch in code that requires ContainerIndexFetch
// 		// and then make assertions.
//
// 	}
type ContainerIndexFetchMock struct {
	// GetImagesFunc mocks the GetImages method.
	GetImagesFunc func(ctx context.Context) (ContainerImages, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetImages holds details about calls to the GetImages method.
		GetImages []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockGetImages sync.RWMutex
}

// GetImages calls GetImagesFunc.
func (mock *ContainerIndexFetchMock) GetImages(ctx context.Context) (ContainerImages, error) {
	if mock.GetImagesFunc == nil {
		panic("ContainerIndexFetchMock.GetImagesFunc: method is nil but ContainerIndexFetch.GetImages was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetImages.Lock()
	mock.calls.GetImages = append(mock.calls.GetImages, callInfo)
	mock.lockGetImages.Unlock()
	return mock.GetImagesFunc(ctx)
}

// GetImagesCalls gets all the calls that were made to GetImages.
// Check the length with:
//     len(mockedContainerIndexFetch.GetImagesCalls())
func (mock *ContainerIndexFetchMock) GetImagesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetImages.RLock()
	calls = mock.calls.GetImages
	mock.lockGetImages.RUnlock()
	return calls
}
