// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package index

import (
	"context"
	"sync"
)

// Ensure, that GCPIndexFetchMock does implement GCPIndexFetch.
// If this is not the case, regenerate this file with moq.
var _ GCPIndexFetch = &GCPIndexFetchMock{}

// GCPIndexFetchMock is a mock implementation of GCPIndexFetch.
//
// 	func TestSomethingThatUsesGCPIndexFetch(t *testing.T) {
//
// 		// make and configure a mocked GCPIndexFetch
// 		mockedGCPIndexFetch := &GCPIndexFetchMock{
// 			GetImagesFunc: func(ctx context.Context, opts FilterOpts) (GCPImages, error) {
// 				panic("mock out the GetImages method")
// 			},
// 		}
//
// 		// use mockedGCPIndexFetch in code that requires GCPIndexFetch
// 		// and then make assertions.
//
// 	}
type GCPIndexFetchMock struct {
	// GetImagesFunc mocks the GetImages method.
	GetImagesFunc func(ctx context.Context, opts FilterOpts) (GCPImages, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetImages holds details about calls to the GetImages method.
		GetImages []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Opts is the opts argument value.
			Opts FilterOpts
		}
	}
	lockGetImages sync.RWMutex
}

// GetImages calls GetImagesFunc.
func (mock *GCPIndexFetchMock) GetImages(ctx context.Context, opts FilterOpts) (GCPImages, error) {
	if mock.GetImagesFunc == nil {
		panic("GCPIndexFetchMock.GetImagesFunc: method is nil but GCPIndexFetch.GetImages was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Opts FilterOpts
	}{
		Ctx:  ctx,
		Opts: opts,
	}
	mock.lockGetImages.Lock()
	mock.calls.GetImages = append(mock.calls.GetImages, callInfo)
	mock.lockGetImages.Unlock()
	return mock.GetImagesFunc(ctx, opts)
}

// GetImagesCalls gets all the calls that were made to GetImages.
// Check the length with:
//     len(mockedGCPIndexFetch.GetImagesCalls())
func (mock *GCPIndexFetchMock) GetImagesCalls() []struct {
	Ctx  context.Context
	Opts FilterOpts
} {
	var calls []struct {
		Ctx  context.Context
		Opts FilterOpts
	}
	mock.lockGetImages.RLock()
	calls = mock.calls.GetImages
	mock.lockGetImages.RUnlock()
	return calls
}
