// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package index

import (
	"context"
	"sync"
)

// Ensure, that OperatorIndexMock does implement OperatorIndex.
// If this is not the case, regenerate this file with moq.
var _ OperatorIndex = &OperatorIndexMock{}

// OperatorIndexMock is a mock implementation of OperatorIndex.
//
//	func TestSomethingThatUsesOperatorIndex(t *testing.T) {
//
//		// make and configure a mocked OperatorIndex
//		mockedOperatorIndex := &OperatorIndexMock{
//			AllFunc: func(ctx context.Context) ([]string, error) {
//				panic("mock out the All method")
//			},
//			LastFunc: func(ctx context.Context) (string, error) {
//				panic("mock out the Last method")
//			},
//			MatchFunc: func(ctx context.Context, version string) (string, error) {
//				panic("mock out the Match method")
//			},
//		}
//
//		// use mockedOperatorIndex in code that requires OperatorIndex
//		// and then make assertions.
//
//	}
type OperatorIndexMock struct {
	// AllFunc mocks the All method.
	AllFunc func(ctx context.Context) ([]string, error)

	// LastFunc mocks the Last method.
	LastFunc func(ctx context.Context) (string, error)

	// MatchFunc mocks the Match method.
	MatchFunc func(ctx context.Context, version string) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// All holds details about calls to the All method.
		All []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Last holds details about calls to the Last method.
		Last []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Match holds details about calls to the Match method.
		Match []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Version is the version argument value.
			Version string
		}
	}
	lockAll   sync.RWMutex
	lockLast  sync.RWMutex
	lockMatch sync.RWMutex
}

// All calls AllFunc.
func (mock *OperatorIndexMock) All(ctx context.Context) ([]string, error) {
	if mock.AllFunc == nil {
		panic("OperatorIndexMock.AllFunc: method is nil but OperatorIndex.All was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockAll.Lock()
	mock.calls.All = append(mock.calls.All, callInfo)
	mock.lockAll.Unlock()
	return mock.AllFunc(ctx)
}

// AllCalls gets all the calls that were made to All.
// Check the length with:
//
//	len(mockedOperatorIndex.AllCalls())
func (mock *OperatorIndexMock) AllCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockAll.RLock()
	calls = mock.calls.All
	mock.lockAll.RUnlock()
	return calls
}

// Last calls LastFunc.
func (mock *OperatorIndexMock) Last(ctx context.Context) (string, error) {
	if mock.LastFunc == nil {
		panic("OperatorIndexMock.LastFunc: method is nil but OperatorIndex.Last was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockLast.Lock()
	mock.calls.Last = append(mock.calls.Last, callInfo)
	mock.lockLast.Unlock()
	return mock.LastFunc(ctx)
}

// LastCalls gets all the calls that were made to Last.
// Check the length with:
//
//	len(mockedOperatorIndex.LastCalls())
func (mock *OperatorIndexMock) LastCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockLast.RLock()
	calls = mock.calls.Last
	mock.lockLast.RUnlock()
	return calls
}

// Match calls MatchFunc.
func (mock *OperatorIndexMock) Match(ctx context.Context, version string) (string, error) {
	if mock.MatchFunc == nil {
		panic("OperatorIndexMock.MatchFunc: method is nil but OperatorIndex.Match was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Version string
	}{
		Ctx:     ctx,
		Version: version,
	}
	mock.lockMatch.Lock()
	mock.calls.Match = append(mock.calls.Match, callInfo)
	mock.lockMatch.Unlock()
	return mock.MatchFunc(ctx, version)
}

// MatchCalls gets all the calls that were made to Match.
// Check the length with:
//
//	len(mockedOperatorIndex.MatchCalls())
func (mock *OperatorIndexMock) MatchCalls() []struct {
	Ctx     context.Context
	Version string
} {
	var calls []struct {
		Ctx     context.Context
		Version string
	}
	mock.lockMatch.RLock()
	calls = mock.calls.Match
	mock.lockMatch.RUnlock()
	return calls
}
