name: Update frontend schemas

on:
    push:
        branches: [main]
        paths: ["schemas/**"]
    workflow_dispatch:

jobs:
    # We have to invoke via repo-dispatch to a private repo so this will not show pass/fail or results here
    ci-trigger-notifications:
        name: Trigger updates on private repos
        runs-on: ubuntu-latest
        permissions:
          contents: none
        steps:
          - name: Trigger ctp-update-schemas Buildkite pipeline
            env:
              BUILDKITE_TRIGGER_WEBHOOK_CTP_UPDATE_SCHEMAS: ${{ secrets.BUILDKITE_TRIGGER_WEBHOOK_CTP_UPDATE_SCHEMAS }}
            run: |
              GH_RUN_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
              curl -fsSL \
                -X POST \
                -d "{\"gh_action_run\":\"$GH_RUN_URL\"}" \
                $BUILDKITE_TRIGGER_WEBHOOK_CTP_UPDATE_SCHEMAS
